
export type Student = {
    id: string;
    name: string;
    class: string;
};

export const classes = ["Avval", "Sani", "Fiqh", "Adab", "Diploma", "Mukthasar", "7th"];

export const students: Student[] = [
    { id: "B13555", name: "MUHAMMAD NABEEL", class: "Avval" },
    { id: "4AF0AF", name: "MUHAD P", class: "Avval" },
    { id: "7FBDE2", name: "MUHAMMAD SALIM", class: "Avval" },
    { id: "3B6750", name: "ABDUL HASEEB", class: "Avval" },
    { id: "1F8C47", name: "MUHAMMAD ASHIK P", class: "Avval" },
    { id: "3807EA", name: "MOHAMMED UBAID K M", class: "Avval" },
    { id: "6DB162", name: "MUHAMMED RABEEH VM", class: "Avval" },
    { id: "D75792", name: "MUHAMMAD SHAHID MP", class: "Avval" },
    { id: "551D13", name: "ABDUL AFEED", class: "Avval" },
    { id: "9EB1CA", name: "AHMED YAMIN", class: "Avval" },
    { id: "BFF845", name: "MUHAMMAD AJMAL.P", class: "Avval" },
    { id: "7DA4EC", name: "MUHAMMED THABSHEER", class: "Avval" },
    { id: "5E036C", name: "MUHAMMAD SINAN TK", class: "Avval" },
    { id: "FF3079", name: "MUHAMMAD AFNAZ", class: "Avval" },
    { id: "B6569C", name: "S MAHAMMAD ALI", class: "Avval" },
    { id: "C8E69F", name: "MUHAMMED NIYAZ", class: "Avval" },
    { id: "91AD9C", name: "MUHAMMAD JUNAID", class: "Avval" },
    { id: "7D2AAF", name: "MUHAMMED SHUHAIB PK", class: "Avval" },
    { id: "3B6CFC", name: "MUHAMMED RIYAS P V", class: "Avval" },
    { id: "AC8A77", name: "SAVAD K", class: "Avval" },
    { id: "E86206", name: "MUHAMMED THAHA", class: "Avval" },
    { id: "377C85", name: "MUHAMMAD UMAIR MA", class: "Avval" },
    { id: "F641A0", name: "Aboobakkar siddiq", class: "Avval" },
    { id: "BE5CFF", name: "FAZAL RAHIMAN. TP", class: "Avval" },
    { id: "DB365A", name: "MUHAMMAD SUHAIL.R", class: "Avval" },
    { id: "E9D244", name: "SAYYID SABITH", class: "Avval" },
    { id: "D43FB5", name: "MUHAMMAD SWALIH V", class: "Avval" },
    { id: "E60DBA", name: "MAHAMMAD SUHAIL N", class: "Avval" },
    { id: "F05869", name: "MUHAMMED JABIR", class: "Avval" },
    { id: "ABA038", name: "MOHAMMED FAVAZ P", class: "Avval" },
    { id: "CFAAA2", name: "MUHAMMAD ZAMEEL", class: "Avval" },
    { id: "309032", name: "SIRAJUDDEEN", class: "Avval" },
    { id: "1DA46B", name: "MUHAMMED HARIS", class: "Avval" },
    { id: "7B863E", name: "MUHAMMED SINAN", class: "Avval" },
    { id: "145F46", name: "AJMAL RASHID", class: "Avval" },
    { id: "8C76D0", name: "MAHAMMED ASIQ", class: "Avval" },
    { id: "AB209A", name: "MUHAMMAD SAFUVAN C", class: "Avval" },
    { id: "452A10", name: "MUHAMMAD SHIBIL", class: "Avval" },
    { id: "B218ED", name: "SALMANUL FARIS", class: "Avval" },
    { id: "972049", name: "MOHAMMED SHUHAIB", class: "Avval" },
    { id: "161208", name: "RUVAIS", class: "Avval" },
    { id: "820F19", name: "Muhammed ajsal k", class: "Avval" },
    { id: "784BFA", name: "MUHAMMED FAIJAS", class: "Avval" },
    { id: "70CC92", name: "MUHAMMAD HIBATHULLAH", class: "Avval" },
    { id: "C3FA8B", name: "Abdu salam", class: "Avval" },
    { id: "1BEEB6", name: "ABDUL HAKEEM TA", class: "Avval" },
    { id: "84040F", name: "Sahal kk", class: "Avval" },
    { id: "F76A2D", name: "MUHAMMED SHAFEEK", class: "Avval" },
    { id: "9AEB9E", name: "MUHAMMED SUFYAN", class: "Avval" },
    { id: "208FCF", name: "MUJEEBURAHMAN", class: "Avval" },
    { id: "440FA0", name: "ABDUL RAHMAN", class: "Avval" },
    { id: "2D28B8", name: "MAHAMMED JAFAR", class: "Avval" },
    { id: "82361E", name: "MUHAMMAD YASIR VP", class: "Avval" },
    { id: "C41894", name: "KHILR", class: "Avval" },
    { id: "B31ECC", name: "BISHRUL HAFi", class: "Avval" },
    { id: "5099A0", name: "MUBASHIR B", class: "Avval" },
    { id: "E39AB3", name: "Mohammad Manzeer", class: "Avval" },
    { id: "7F5150", name: "MUHAMMAD ADIL", class: "Avval" },
    { id: "A2575B", name: "MUHAMMED ASLAM", class: "Avval" },
    { id: "F863C4", name: "MUHAMMED SAYEED M", class: "Avval" },
    { id: "61BAE1", name: "MUHAMMAD SABITH", class: "Avval" },
    { id: "7B4B2C", name: "MUHAMMED RAFSAL CN", class: "Avval" },
    { id: "393BCA", name: "Muhammad Rafi tc", class: "Avval" },
    { id: "6C4B0B", name: "AJMALJ", class: "Avval" },
    { id: "7CA67F", name: "MUHAMMED FAYIS TK", class: "Avval" },
    { id: "E359B8", name: "ABDUL RAZI", class: "Avval" },
    { id: "499F31", name: "AHAMMED LABEEB.KP", class: "Avval" },
    { id: "1888A7", name: "SHAMSHUDDIN K", class: "Avval" },
    { id: "18FD8F", name: "ADHIL USMAN", class: "Avval" },
    { id: "A14A2F", name: "IQBAL HUSAIN", class: "Avval" },
    { id: "6FBC01", name: "MUHAMMED DILSHAD. P", class: "Avval" },
    { id: "F72D03", name: "ASHRAF ALI VM", class: "Avval" },
    { id: "613A4D", name: "SAVAD TK", class: "Avval" },
    { id: "A63F43", name: "MOHAMMED THABREEZ", class: "Avval" },
    { id: "AF5F58", name: "MUHAMMAD AFSAL", class: "Avval" },
    { id: "D5802A", name: "ABBAS NAWSHAD", class: "Avval" },
    { id: "23534E", name: "MOHAMMAD ANEES", class: "Avval" },
    { id: "B49457", name: "MUHAMMED ANAS", class: "Avval" },
    { id: "5776E9", name: "MUHAMMAD SHAMEEM PK", class: "Avval" },
    { id: "91118E", name: "MUHAMMAD SWADIQ P", class: "Avval" },
    { id: "3F019D", name: "Hassan nafih", class: "Avval" },
    { id: "A4A70C", name: "MUHAMMAD SIYAD .PT", class: "Avval" },
    { id: "FD2B46", name: "MUHAMMED SUHAIL", class: "Avval" },
    { id: "296411", name: "MUHAMMAD SHAFEEK", class: "Avval" },
    { id: "2292AD", name: "MUHAMMED SALMAN. L", class: "Avval" },
    { id: "E761FA", name: "AHMADULKABEER CP", class: "Avval" },
    { id: "270C6C", name: "SAYYED IBRAHIM KHALEEL", class: "Avval" },
    { id: "DFDF2A", name: "MAHAMMAD SAVAD", class: "Avval" },
    { id: "5549FE", name: "SHAMSAD P", class: "Avval" },
    { id: "C5DF7A", name: "MOHAMMED RAEES", class: "Avval" },
    { id: "A7B281", name: "ALI ASHHAR", class: "Avval" },
    { id: "17EA09", name: "AJMAL TM", class: "Avval" },
    { id: "C6F264", name: "SAFWAN K", class: "Avval" },
    { id: "9D7760", name: "AHAMMED ANWAR", class: "Avval" },
    { id: "2D9090", name: "YAHYA MP", class: "Avval" },
    { id: "9CD198", name: "HASAINAR K", class: "Avval" },
    { id: "AC5AB3", name: "MUHAMMED SUHAIL KC", class: "Avval" },
    { id: "CB0680", name: "Mahammad shakeel kh", class: "Avval" },
    { id: "93932F", name: "MUHAMMED SHANID PM", class: "Avval" },
    { id: "B25646", name: "JABIR N A", class: "Avval" },
    { id: "3815D6", name: "SHAMSUDDIN", class: "Avval" },
    { id: "1F3AE2", name: "ABDUL BASITH", class: "Avval" },
    { id: "2380EC", name: "Mohammed ramshad p", class: "Avval" },
    { id: "8F7A5E", name: "MUHAMMAD MUZZAMMIL C.T", class: "Avval" },
    { id: "EDF20C", name: "NAZEER", class: "Avval" },
    { id: "902B8C", name: "SUHAIL KHAN", class: "Avval" },
    { id: "7FEE61", name: "NAWAL MARJAN.C", class: "Avval" },
    { id: "8965F2", name: "YAHYA", class: "Avval" },
    { id: "963749", name: "MUHAMMED AFSAL LAKKAL", class: "Avval" },
    { id: "DA7EB6", name: "Muhammed muhsin", class: "Avval" },
    { id: "7FF3D0", name: "MUHAMMAD FAISAL", class: "Avval" },
    { id: "55F112", name: "SAYYID ABDUL KHADAR JALALUDHEEN", class: "Avval" },
    { id: "A3D887", name: "ABU THALHA", class: "Avval" },
    { id: "D5DD47", name: "MUHAMMAD RAFI", class: "Avval" },
    { id: "FAAE25", name: "JAMALUDDIN", class: "Avval" },
    { id: "8AA150", name: "MUHAMMED SN", class: "Avval" },
    { id: "165FED", name: "Ajmal", class: "Avval" },
    { id: "B56E8E", name: "MAHAMMAD MUNAVAR", class: "Avval" },
    { id: "23F13C", name: "MOHAMMED NISHAD MT", class: "Avval" },
    { id: "E5A35D", name: "MOHAMMAD SAMEER", class: "Avval" },
    { id: "CD79B2", name: "ANEESUDHEEN", class: "Avval" },
    { id: "459302", name: "MUHAMMED JUNAID", class: "Avval" },
    { id: "8E6D55", name: "Suhail pm", class: "Avval" },
    { id: "F285A3", name: "SHIHABUDDIN", class: "Avval" },
    { id: "D89D95", name: "MUHAMMAD SAVAD KC", class: "Avval" },
    { id: "E410ED", name: "ANAS MUHIYADDIN", class: "Avval" },
    { id: "D9E588", name: "Mohammed Abdul basith", class: "Avval" },
    { id: "AC34C6", name: "MUHAMMAD RAZI R", class: "Avval" },
    { id: "7972C7", name: "MUHAMMAD ALTHAF", class: "Avval" },
    { id: "8F61F4", name: "MAHAMMAD SHAHEER P.A", class: "Avval" },
    { id: "A5F125", name: "MUHAMMAD SUFIYAN ALI", class: "Avval" },
    { id: "E8F6D7", name: "MUHAMMED SAHAL K", class: "Avval" },
    { id: "F32637", name: "MOHAMMAD SABITH", class: "Avval" },
    { id: "9CCC3D", name: "Muhammad shahid k", class: "Avval" },
    { id: "531DD7", name: "MUHIYIDDEEN", class: "Avval" },
    { id: "A3DE37", name: "ABDURAHMAN HOUF", class: "Avval" },
    { id: "1C070A", name: "MUHAMMED BILAL K", class: "Avval" },
    { id: "CB6E31", name: "JALALUDDIN KM", class: "Avval" },
    { id: "DD2472", name: "MUHAMMAD MUHAD", class: "Avval" },
    { id: "4968E6", name: "MUHAMMAD SHAMEEM", class: "Avval" },
    { id: "59592F", name: "MUHAMMED SWALIH CP", class: "Avval" },
    { id: "545FA6", name: "V MOHAMMED  TWAHEER", class: "Avval" },
    { id: "893E45", name: "MUHAMMED RABEEH", class: "Avval" },
    { id: "2ABD43", name: "MUHAMMED SINAN T", class: "Avval" },
    { id: "2769EA", name: "MUHAMMED MUBASHIR. K", class: "Avval" },
    { id: "F5875C", name: "FAISAL CT", class: "Avval" },
    { id: "8384D2", name: "ABDUL JABBAR ASIF", class: "Avval" },
    { id: "8430FF", name: "MUHAMMED SHAFEEQ P", class: "Avval" },
    { id: "D18E38", name: "ABDUL RASHEED K", class: "Avval" },
    { id: "A5BFA5", name: "ABDULL BASITH", class: "Avval" },
    { id: "85A1D4", name: "MUHAMMAD IRSHAD", class: "Avval" },
    { id: "588331", name: "MUHAMMAD ASHIQ", class: "Avval" },
    { id: "86CEE3", name: "MUHAMMED RAMSHID TP", class: "Avval" },
    { id: "D56122", name: "MUHAMMED SAHL PP", class: "Avval" },
    { id: "BFF162", name: "MUHAMMED JASIR PK", class: "Avval" },
    { id: "D26E6F", name: "MUHAMMED RAMEES EK", class: "Avval" },
    { id: "18A232", name: "MUHAMMED ANAS PY", class: "Avval" },
    { id: "364666", name: "MUHAMMED SABITH A", class: "Avval" },
    { id: "EC9420", name: "FILTHAR", class: "Avval" },
    { id: "D9F3BD", name: "JAFAR SADIQUE VP", class: "Avval" },
    { id: "492F14", name: "HAZARATH KALANDHARSHA P", class: "Avval" },
    { id: "91D770", name: "SAVAD CH", class: "Avval" },
    { id: "21CB55", name: "MUHAMMED MUSLIH MO", class: "Avval" },
    { id: "41FB45", name: "JAFER", class: "Avval" },
    { id: "3E3199", name: "MUHAMMED ABDUL BARI", class: "Avval" },
    { id: "D2A7D4", name: "MUHAMMED RASHID. P", class: "Avval" },
    { id: "1654C9", name: "MUHAMMED BUJAIR P", class: "Avval" },
    { id: "F5A3A4", name: "MUHMMED SANIF", class: "Avval" },
    { id: "C4B4A8", name: "MAHAMMAD THWAHA SHAFEEQ", class: "Avval" },
    { id: "F9AE6B", name: "MARVAN P", class: "Avval" },
    { id: "175844", name: "MOHAMMED HANAS", class: "Avval" },
    { id: "6AD4BE", name: "ABDUL MASHOOD", class: "Avval" },
    { id: "D070CA", name: "Ahmed kabeer k.p", class: "Avval" },
    { id: "1D197A", name: "MUHAMMED RABEEH", class: "Avval" },
    { id: "2BD4A3", name: "MUHAMMED BINYAMIN", class: "Avval" },
    { id: "9966EA", name: "MUHAMMED SWALIH T", class: "Avval" },
    { id: "B7BBEE", name: "ZABIULLAH", class: "Avval" },
    { id: "D83E24", name: "MUHAMMAD RIYAZ", class: "Avval" },
    { id: "6D563D", name: "MUHAMMED SAEEDH K", class: "Avval" },
    { id: "1B6B65", name: "MOHAMMED BISHUR KC", class: "Avval" },
    { id: "2A9201", name: "FAKRUDDEEN JISTHI", class: "Sani" },
    { id: "311E10", name: "BADUSHA VN", class: "Sani" },
    { id: "B91CA7", name: "SHANAVAS", class: "Sani" },
    { id: "5BDEDD", name: "MUHAMMED RASHAD MP", class: "Sani" },
    { id: "485A3E", name: "MUHAMMAD JABIR K.P", class: "Sani" },
    { id: "287A13", name: "MUHAMMED SUHAIL T", class: "Sani" },
    { id: "D7B18F", name: "Muhammed Yoosuful Farooq", class: "Sani" },
    { id: "B54AFF", name: "MOHAMMAD NOUFAL", class: "Sani" },
    { id: "54A916", name: "ABDUL MISBAH RUFAID", class: "Sani" },
    { id: "DD64D8", name: "MUHAMMED RASHID CM", class: "Sani" },
    { id: "834EA2", name: "MUAD", class: "Sani" },
    { id: "8997E3", name: "MOHAMMED UVAIS TT", class: "Sani" },
    { id: "FF5A90", name: "MUHAMMAD FASLU RAHMAN", class: "Sani" },
    { id: "64C44A", name: "ABDUL SAMAD", class: "Sani" },
    { id: "5F4C5E", name: "SAIFUDDEEN C A", class: "Sani" },
    { id: "DF8A33", name: "AJMAL EP", class: "Sani" },
    { id: "CFFCFD", name: "MUHAMMAD RIFA-ATH T.G", class: "Sani" },
    { id: "B02CB5", name: "SAYYID JAMALUDHEEN ATAKOYA THANGAL", class: "Sani" },
    { id: "8C2FA1", name: "MOHAMMED IMRAN", class: "Sani" },
    { id: "8126FB", name: "MUHAMMAD NABEEL", class: "Sani" },
    { id: "579FE3", name: "MOHAMMED MASHOOD P", class: "Sani" },
    { id: "EDFC70", name: "MAHAMMAD ANWER SABITH", class: "Sani" },
    { id: "DCC7ED", name: "MOHAMMED MUNAZ", class: "Sani" },
    { id: "B071EC", name: "MUHAMMAD HASIR", class: "Sani" },
    { id: "A6B705", name: "MUHAMMED SHAMMAS A I", class: "Sani" },
    { id: "3E9AFE", name: "MUHAMMAD CP", class: "Sani" },
    { id: "792C23", name: "MUNAVVIR", class: "Sani" },
    { id: "CDB707", name: "MANSOOR BA", class: "Sani" },
    { id: "56DD58", name: "ABDUL RAHIMAN KH", class: "Sani" },
    { id: "203A74", name: "MOHAMMAD UNAIZ", class: "Sani" },
    { id: "443FB1", name: "MUHAMMED ZUHAIB", class: "Sani" },
    { id: "FBCC83", name: "MOIDIN JAFAR", class: "Sani" },
    { id: "31DFD8", name: "MOHAMMED SAHAD", class: "Sani" },
    { id: "6B7619", name: "ABDUL MUSAWIR", class: "Sani" },
    { id: "7FC605", name: "ABDUL AZEEZ V", class: "Sani" },
    { id: "5B75D2", name: "MOHAMMED SHAMSUDDIN", class: "Sani" },
    { id: "309410", name: "ABDUL RAHIMAN RAAIZ", class: "Sani" },
    { id: "87A508", name: "DHAUDUL HAKEEM", class: "Sani" },
    { id: "31E61F", name: "MUHAMMAD SUHAIL", class: "Sani" },
    { id: "8F4CA7", name: "RIYAZ", class: "Sani" },
    { id: "D49A38", name: "MUHAMMAD MURSHID A B", class: "Sani" },
    { id: "DDB3D0", name: "MUHAMMED ASHIQUE TT", class: "Sani" },
    { id: "955C35", name: "MOHAMMED NOUFAL KM", class: "Sani" },
    { id: "1D50D8", name: "MOHAMMED FAYYAZ AP", class: "Sani" },
    { id: "6046CE", name: "Muhammad Shareef ps", class: "Sani" },
    { id: "13D3D4", name: "AJMAL T. M", class: "Sani" },
    { id: "D37338", name: "MUHAMMED SHIBILI. T", class: "Sani" },
    { id: "F27C02", name: "MUHAMMAD SHUHAIB", class: "Sani" },
    { id: "378B81", name: "ASLAM MA", class: "Sani" },
    { id: "534B68", name: "MUHAMMED RAHEES. KK", class: "Sani" },
    { id: "1C3C1F", name: "MUHAMMED NAFIH", class: "Sani" },
    { id: "5771CA", name: "MUHAMMED NIYAS", class: "Sani" },
    { id: "E3D355", name: "MUHAMMAD RASHID VS", class: "Sani" },
    { id: "242D71", name: "MOHAMMAD HARIS. N", class: "Sani" },
    { id: "9654DC", name: "ANWAR SHAREEF", class: "Sani" },
    { id: "5BA1A0", name: "MUHAMAD RASHID PM", class: "Sani" },
    { id: "7B61E3", name: "IRSHAD A.M", class: "Sani" },
    { id: "B8BB7B", name: "MOHAMMED HARIS", class: "Sani" },
    { id: "93ECD9", name: "Mubashir", class: "Sani" },
    { id: "8DEADB", name: "NOUSHAD FARHAN", class: "Sani" },
    { id: "DAE186", name: "AHMED", class: "Sani" },
    { id: "93B11C", name: "MUHAMMED SINAN", class: "Sani" },
    { id: "6E90D7", name: "ISHAQ", class: "Sani" },
    { id: "F71019", name: "JABIR", class: "Sani" },
    { id: "356868", name: "MUHAMMED AMIR. N", class: "Sani" },
    { id: "49B389", name: "MUHAMMED SHIBILI VK", class: "Sani" },
    { id: "EEA419", name: "P.U MUHAMMAD THWALHATH ANWAR", class: "Sani" },
    { id: "1302BF", name: "MUHAMMED YOUSUF", class: "Sani" },
    { id: "7C583F", name: "SHAHIR", class: "Sani" },
    { id: "E69C31", name: "MUHAMMED MIDLAJ OK", class: "Sani" },
    { id: "9648B1", name: "ABDUL RAHMAN SAHAD", class: "Sani" },
    { id: "6A4B73", name: "SAYYID MUHAMMAD SHAMMAS AL HADI", class: "Sani" },
    { id: "5518AB", name: "MUHAMMAD ALI K", class: "Sani" },
    { id: "9B5154", name: "MAHAMMAD JABIR", class: "Sani" },
    { id: "B9D4DC", name: "HYDAR ALI", class: "Sani" },
    { id: "3C9079", name: "MOHAMMED SHIFAN", class: "Sani" },
    { id: "EEC7FC", name: "SAYYID MOHAMMAD ASHRAF", class: "Sani" },
    { id: "B85B5E", name: "MOHAMMED AFEEF K", class: "Sani" },
    { id: "61CF3B", name: "AMEER", class: "Sani" },
    { id: "9876CE", name: "MUHAMMED MUJEEB", class: "Sani" },
    { id: "DD9A5E", name: "ABDUL JALEEL", class: "Sani" },
    { id: "2C61F6", name: "MOHAMMED HARIS.B", class: "Sani" },
    { id: "43C7DB", name: "MUHAMMAD RAFEEK", class: "Sani" },
    { id: "23D6DF", name: "MUHAMMED SALMAN", class: "Sani" },
    { id: "9CBB33", name: "KHALEELURAHMAN", class: "Sani" },
    { id: "44379D", name: "MOHAMMED SHANIH N", class: "Sani" },
    { id: "C03FDF", name: "ABDUL JALEEL", class: "Sani" },
    { id: "5979C7", name: "MUHAMMED NAVAS P", class: "Sani" },
    { id: "4A2086", name: "RAEESUL AKBAR", class: "Sani" },
    { id: "C416B7", name: "MOHMMAD SINAN", class: "Sani" },
    { id: "442DB7", name: "MUHAMMAD NAJEEB P.A", class: "Sani" },
    { id: "8F4FE0", name: "NASRULLA", class: "Sani" },
    { id: "E9DC76", name: "MUHAMMED BISHRUL HAFI", class: "Sani" },
    { id: "3F2EEA", name: "ABDUL FATHAH CP", class: "Sani" },
    { id: "CC87B3", name: "MUHAMMED IHSAN K K", class: "Sani" },
    { id: "F14DA1", name: "MOHAMMED SHIHAB", class: "Sani" },
    { id: "501478", name: "SIRAJUDHEEN SAHEED C", class: "Sani" },
    { id: "A39DA4", name: "AHMAD SAEED", class: "Sani" },
    { id: "F99AEA", name: "MUHAMMAD MINHAJ", class: "Sani" },
    { id: "E1D78D", name: "Mohamed Favas", class: "Sani" },
    { id: "A9E250", name: "RIMSHAD AM", class: "Sani" },
    { id: "7568BA", name: "MUHAMMED SUFIYAN PK", class: "Sani" },
    { id: "AED040", name: "MOHAMMED UNAIS. P", class: "Sani" },
    { id: "D0E22D", name: "SARFUDDIN", class: "Sani" },
    { id: "2DFE9D", name: "MUHAMMAD NASIM CP", class: "Sani" },
    { id: "5B0DE8", name: "MUHAMMAD FAIZ MG", class: "Sani" },
    { id: "E9DD74", name: "MOHAMMAD ANSAR.N", class: "Sani" },
    { id: "66A6E0", name: "ISMAIL SHAFI", class: "Sani" },
    { id: "3630E4", name: "MUHAMMAD UNAIS", class: "Sani" },
    { id: "99B631", name: "NAJEEB RAHMAN KS", class: "Sani" },
    { id: "CA3C17", name: "MUHAMMAD VASIL", class: "Sani" },
    { id: "760A6F", name: "MUHAMMAD FASIL KP", class: "Sani" },
    { id: "921CEB", name: "MUHAMMED SHAREEF", class: "Sani" },
    { id: "6E17DF", name: "MAHAMMAD ALI", class: "Sani" },
    { id: "5F1C4A", name: "HAFIZ CM ABOOBACKER JUNAID", class: "Sani" },
    { id: "8D8E40", name: "MOHAMMAD SALIH T", class: "Sani" },
    { id: "9B214E", name: "MUHEMMAD NABEEL KV", class: "Sani" },
    { id: "618E1C", name: "MOHAMMED FAHEEM", class: "Sani" },
    { id: "8EE520", name: "SIDDIK", class: "Sani" },
    { id: "FBE105", name: "AHAMMED SALEEM T", class: "Sani" },
    { id: "CF972A", name: "Ashik", class: "Sani" },
    { id: "30E8F2", name: "MOHAMMED MUSTAFA K I", class: "Sani" },
    { id: "E7B088", name: "MUHAMMED ASHIQUE. T", class: "Sani" },
    { id: "36DFCD", name: "MOHAMMED SUFYAN KP", class: "Sani" },
    { id: "71DEBF", name: "MUHAMMED MUDHASIR KT", class: "Sani" },
    { id: "F3F4A4", name: "MUHAMMAD MUSTHAFA KP", class: "Sani" },
    { id: "840CA4", name: "MUBASHIR", class: "Sani" },
    { id: "C91450", name: "MUHAMMED SHAFI KP", class: "Sani" },
    { id: "8540EE", name: "MUHAMMAD ARSHID A", class: "Sani" },
    { id: "F1B32B", name: "MUHAMMED SHAFEEK.S", class: "Sani" },
    { id: "CAA85C", name: "SHIHABUDHEEN.M", class: "Sani" },
    { id: "CA7962", name: "MOHAMMED RISHAN", class: "Sani" },
    { id: "B7C960", name: "MUHAMMED UVAIS.KP", class: "Sani" },
    { id: "8DBEC9", name: "Ahammad Ameen T", class: "Sani" },
    { id: "1A6D23", name: "MUHAMMAAD FAZIL P", class: "Sani" },
    { id: "A58A5A", name: "RAMSHEED A", class: "Sani" },
    { id: "34D959", name: "FADHALU RAHMAN PK", class: "Sani" },
    { id: "CF488A", name: "MUHAMMED SHAMEEM", class: "Sani" },
    { id: "AEE3B8", name: "MUHAMMED YASEEN.K", class: "Sani" },
    { id: "915E60", name: "MUZAMMIL PM", class: "Sani" },
    { id: "104EEC", name: "MURSHID ABDUL KHADER C", class: "Sani" },
    { id: "E9A194", name: "B. MAHAMMAD ANAS", class: "Sani" },
    { id: "F29DDC", name: "MOHAMMED SAHAD", class: "Sani" },
    { id: "8CCC7A", name: "SHEFEEQ PT", class: "Sani" },
    { id: "35B899", name: "MUHAMMED AFSAL P A", class: "Sani" },
    { id: "B93A22", name: "MUHAMMED SHAFI CM", class: "Sani" },
    { id: "2EBABF", name: "MUHAMMAD SUHAIL ASWAN", class: "Sani" },
    { id: "355131", name: "P M S A HUSSAIN THANGAL", class: "Sani" },
    { id: "9A2913", name: "MUHAMMED SALIM PK", class: "Sani" },
    { id: "E67D15", name: "MUHAMMED JABIR K", class: "Sani" },
    { id: "2F7822", name: "ABDULLA CP", class: "Sani" },
    { id: "DEAAC0", name: "HAFIZ MUHAMMAD SHUHAIB PK", class: "Sani" },
    { id: "79DB28", name: "MUHAMMAD SWADIK", class: "Sani" },
    { id: "11EAEB", name: "AHAMMAD SHAMMAS", class: "Sani" },
    { id: "FE1DF5", name: "SHAKKIR. S", class: "Sani" },
    { id: "45DC95", name: "SHAFEEQUE M. M", class: "Sani" },
    { id: "ACF197", name: "MOHAMMED NASARUDDEEN", class: "Sani" },
    { id: "125311", name: "MUHAMMAD HASAN SA-ADI", class: "Fiqh" },
    { id: "D86E67", name: "MAHAMMED BATHISHA P A", class: "Fiqh" },
    { id: "2B871A", name: "MUHAMMAD HUSSAIN", class: "Fiqh" },
    { id: "183AC8", name: "JULAIB AHAMMED KP", class: "Fiqh" },
    { id: "F70659", name: "MUHAMMAD ABOOBACKAR P", class: "Fiqh" },
    { id: "A5202F", name: "SADAQATHULLA", class: "Fiqh" },
    { id: "EE3CA0", name: "MUHAMMED SAVAD ADANY", class: "Fiqh" },
    { id: "BFFC2C", name: "MUHAMMAD SHAHID KM", class: "Fiqh" },
    { id: "4C5983", name: "MUHAMMED SINAN AV", class: "Fiqh" },
    { id: "EBC50C", name: "AKBAR ALI", class: "Fiqh" },
    { id: "D5B83B", name: "MUHAMMED FAROOK", class: "Fiqh" },
    { id: "7B6545", name: "MUHAMMED SHAMSUDHEEN N", class: "Fiqh" },
    { id: "20CAB7", name: "SAYYID SUHAIL KMP", class: "Fiqh" },
    { id: "6CDA3F", name: "ASHIK MUHAMMED A.J", class: "Fiqh" },
    { id: "33978B", name: "ADAM.S", class: "Fiqh" },
    { id: "376617", name: "MUHAMMED SABITH MT", class: "Fiqh" },
    { id: "7C98CB", name: "ISMAIL YASIR", class: "Fiqh" },
    { id: "CC9CF3", name: "MUHAMMAD SHAREEF", class: "Fiqh" },
    { id: "3D743E", name: "MUHAMMAD SHAREEF KB", class: "Fiqh" },
    { id: "5F40F6", name: "MUHAMMAD SHAHID", class: "Fiqh" },
    { id: "F49739", name: "MOHAMMED ANAS.H", class: "Adab" },
    { id: "B89867", name: "MUHAMMAD ISMAIL", class: "Adab" },
    { id: "6EF633", name: "MUHAMMED SUHAIL TA", class: "Adab" },
    { id: "904B8C", name: "MUHAMMAD SHUHAIB CM", class: "Adab" },
    { id: "3B85A8", name: "MOHAMMED SHAMSHAD M", class: "Adab" },
    { id: "84BFC7", name: "FAZALU RAHMAN", class: "Adab" },
    { id: "B8B316", name: "MOHAMMAD MAQBOOL", class: "Adab" },
    { id: "14EEF4", name: "AJMAL PP", class: "Adab" },
    { id: "D32DD9", name: "MUHAMMED SAFWAN ABOOBACKER", class: "Adab" },
    { id: "614183", name: "RASHIDALI N", class: "Adab" },
    { id: "226C66", name: "MUHAMMED HIDAYATHULLAH KK", class: "Adab" },
    { id: "A112CD", name: "MUHAMMED SAIED", class: "Adab" },
    { id: "6006F1", name: "MUHAMMED SINAN PP", class: "Adab" },
    { id: "BE1E13", name: "THWALHA SAQAFI", class: "Adab" },
    { id: "9478AD", name: "MUHAMMED SARFARAS", class: "Adab" },
    { id: "DFBB22", name: "MUHAMMED ASHIK", class: "Diploma" },
    { id: "C718E7", name: "ASHAB.K", class: "Diploma" },
    { id: "F4E7FE", name: "MUHAMMED FAYASUDHEEN.K.R", class: "Diploma" },
    { id: "14E0E5", name: "ABDUL RAHMAN K.S", class: "Diploma" },
    { id: "CEBD0B", name: "JAMALUDEEN", class: "Diploma" },
    { id: "D65707", name: "FARHAN BM", class: "Diploma" },
    { id: "F3EF0C", name: "Mohammad Abdul razzaque khan", class: "Diploma" },
    { id: "C8F6CD", name: "AHMAD RAZA KHAN", class: "Diploma" },
    { id: "7A09E6", name: "Gulam mustafa", class: "Diploma" },
    { id: "93A464", name: "BASRUDDIN RAZAVI", class: "Diploma" },
    { id: "18747C", name: "SAJID ALI", class: "Diploma" },
    { id: "5BE52D", name: "MOINUDDEN QADRI", class: "Diploma" },
    { id: "842D03", name: "MD AFZAL ARBI", class: "Diploma" },
    { id: "1E3113", name: "ISHAQ SAQIB ADHAL", class: "Diploma" },
    { id: "C76221", name: "JAMSED AHMAD", class: "Diploma" },
    { id: "65F6CA", name: "IBRAHIM SK", class: "Diploma" },
    { id: "1D33AC", name: "JASEEM RAZA", class: "Diploma" },
    { id: "80DB1B", name: "MD RONI SK", class: "Diploma" },
    { id: "B55A4B", name: "MD SHAKIR ALI", class: "Diploma" },
    { id: "D70D01", name: "RAFIK ANSARI", class: "Diploma" },
    { id: "A4535D", name: "HARIS MOHAMED", class: "Diploma" },
    { id: "1AB9F4", name: "MD PARVEJ", class: "Diploma" },
    { id: "4FD24C", name: "SAEED KHAN", class: "Diploma" },
    { id: "D8FAE4", name: "MAUHAMMAD SHAREEF PA", class: "Mukthasar" },
    { id: "333E20", name: "JAMALUDHHEEN KA", class: "Mukthasar" },
    { id: "8CF772", name: "EBRAHIM BADUSHA", class: "Mukthasar" },
    { id: "F94592", name: "ABDUL RAHMAN B.H", class: "Mukthasar" },
    { id: "FC35AC", name: "MAHAMMAD ASHIK", class: "Mukthasar" },
    { id: "6C30CE", name: "MOHAMMED SALMANUL FARIS", class: "Mukthasar" },
    { id: "6A9500", name: "MUHAMMED IQBAL", class: "Mukthasar" },
    { id: "2A6B1D", name: "THAHIR", class: "Mukthasar" },
    { id: "FA8773", name: "MUHAMMED SAVAD", class: "Mukthasar" },
    { id: "856334", name: "SAYID MUHLAR MUS'AB THANGAL", class: "7th" },
    { id: "17B808", name: "AHAMMAD AZARUDDIN", class: "7th" },
    { id: "B9B340", name: "MOHAMMAD SUHAIL", class: "7th" },
    { id: "B02D0A", name: "ABDUL MAJID K A", class: "7th" },
    { id: "F59DF0", name: "SAHAD B E", class: "7th" },
    { id: "7A9472", name: "SWADHIQ", class: "7th" },
    { id: "692F8D", name: "Muhammad Shammas", class: "7th" },
];
